                                                                            --TN_DBM_ENTRPRS_BASS_INFO

                                                                            INSERT INTO TN_DBM_ENTRPRS_BASS_INFO(
                                                                                BSNM_REGIST_NO,
                                                                                VALID_END_PNTTM,
                                                                                VALID_BEGIN_PNTTM,
                                                                                CPR_REGIST_NO,
                                                                                CPR_NM,
                                                                                ENTRPRS_NM,
                                                                                RPRSNTV_NM,
                                                                                ROAD_ADRES,
                                                                                ROAD_DETAIL_ADRES,
                                                                                LNM_ADRES,
                                                                                LNM_DETAIL_ADRES,
                                                                                ZIP,
                                                                                TLPHON_NO,
                                                                                FAX_NO,
                                                                                EMAIL_ADRES,
                                                                                FOND_DE,
                                                                                SSS_BIZQIT_DE,
                                                                                NTS_INFO_RECPTN_AT,
                                                                                STD_INDUST_CL_IEM_CODE_CN,
                                                                                MAIN_PRODUCT_CN, CPR_AT,
                                                                                ENTRPRS_OTHBC_CODE,
                                                                                ENTRPRS_STTUS_CODE,
                                                                                ENTRPRS_STLE_CODE,
                                                                                ENTRPRS_SCALE_CODE,
                                                                                HMPG_ADRES,
                                                                                ENTRPRS_ENG_NM,
                                                                                CREDT_GRAD_ID,
                                                                                NICE_ID,
                                                                                RLTPSN_CODE,
                                                                                INFO_ORIGIN_CODE,
                                                                                CNTC_PROCESS_DT,
                                                                                OPERT_STTUS_CODE,
                                                                                USE_AT,
                                                                                PROGRM_ID,
                                                                                CREATR_ID,
                                                                                CREAT_PNTTM,
                                                                                UPDUSR_ID,
                                                                                UPDT_PNTTM 
                                                                            ) VALUE (
                                                                                #bsnmRegistNo#,
                                                                                #validEndPnttm#,
                                                                                #validBeginPnttm#,
                                                                                #cprRegistNo#,
                                                                                #cprNm#,
                                                                                #entrprsNm#,
                                                                                #rprsntvNm#,
                                                                                #roadAdres#,
                                                                                #roadDetailAdres#,
                                                                                #lnmAdres#,
                                                                                #lnmDetailAdres#,
                                                                                #zip#,
                                                                                #tlphonNo#,
                                                                                #faxNo#,
                                                                                #emailAdres#,
                                                                                #fondDe#,
                                                                                #sssBizqitDe#,
                                                                                nts_info_recptn_at
                                                                                '', --국세청정보 nts_info_recptn_at 
                                                                                #stdIndustClIem_codeCn#,
                                                                                #mainProductCn#,
                                                                                #cprAt#,
                                                                                #entrprsOthbcCode#,
                                                                                #entrprsSttusCode$#,
                                                                                #entrprsStleCode#,
                                                                                #entrprsScaleCode#,
                                                                                #hmpgAdres#,
                                                                                entrprs_eng_nm, --기업체영문명 entrprs_eng_nm 
                                                                                #credtGradId#,
                                                                                '', --nice_id
                                                                                #rltpsnCode#,
                                                                                #infoOriginCode#,
                                                                                '', --연계처리일시 
                                                                                '', --작업상태코드 
                                                                                #useAt#,
                                                                                #progrmId#,
                                                                                #creatrId#,
                                                                                #creatPnttm#,
                                                                                #updusrId#,
                                                                                #updtPnttm# 
                                                                            );
